version: "3.7"

services:
  adianti_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-apache      
    volumes:
      - .:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      - ./php/php.ini:/usr/local/etc/php/php.ini  # Volume para editar o php.ini
      #- adianti_html:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      #- adianti_php:/usr/local/etc/php  # Volume para editar o php.ini
    ports:
      - "8080:80"
    networks:
      - network_public      
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.adianti_app.rule=Host(`${URL_TRAEFIK}`)
        - traefik.http.routers.adianti_app.entrypoints=websecure
        - traefik.http.routers.adianti_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.adianti_app.service=portal
        - traefik.http.services.adianti_app.loadbalancer.server.port=80
        - traefik.http.services.adianti_app.loadbalancer.passHostHeader=true
 
volumes:
  adianti_html:
    external: true
    name: adianti_html      
  adianti_php:
    external: true
    name: adianti_php 
networks:
  network_public:
    external: true  
