version: "3.7"

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-apache      
    volumes:
      #- .:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      #- ./php/php.ini:/usr/local/etc/php/php.ini  # Volume para editar o php.ini
      - portal_html:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      - portal_php:/usr/local/etc/php  # Volume para editar o php.ini
    ports:
      - "8080:80"
    networks:
      #- network_public
      - network_public
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.portal.rule=Host(`portal.bjsoft.com.br`)
        - traefik.http.routers.portal.entrypoints=websecure
        - traefik.http.routers.portal.tls.certresolver=letsencryptresolver
        - traefik.http.routers.portal.service=portal
        - traefik.http.services.portal.loadbalancer.server.port=80
        - traefik.http.services.portal.loadbalancer.passHostHeader=true
 
volumes:
  portal_html:
    external: true
    name: portal_html      
  portal_php:
    external: true
    name: portal_php 
    
networks:
  network_public:
    external: true  
