version: "3.7"

services:
  ${DOC_NAME}:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-apache      
    volumes:
      #- .:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      #- ./php/php.ini:/usr/local/etc/php/php.ini  # Volume para editar o php.ini
      - ${DOC_NAME}_html:/var/www/html  # Monta o diretório do projeto dentro do container PHP
      - ${DOC_NAME}_php:/usr/local/etc/php  # Volume para editar o php.ini
    ports:
      - "8080:80"
    networks:
      #- network_public
      - ${DOC_NET}
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.${DOC_NAME}.rule=Host(`${URL_TRAEFIK}`)
        - traefik.http.routers.${DOC_NAME}.entrypoints=websecure
        - traefik.http.routers.${DOC_NAME}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.${DOC_NAME}.service=portal
        - traefik.http.services.${DOC_NAME}.loadbalancer.server.port=80
        - traefik.http.services.${DOC_NAME}.loadbalancer.passHostHeader=true
 
volumes:
  ${DOC_NAME}_html:
    external: true
    name: ${DOC_NAME}_html      
  ${DOC_NAME}_php:
    external: true
    name: ${DOC_NAME}_php 
    
networks:
  ${DOC_NET}:
    external: true  
